"""mot de passe fournisseur

Revision ID: 0d684c418783
Revises: 84f8151f7c9e
Create Date: 2026-07-17 16:58:34.019480

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0d684c418783'
down_revision: str | None = '84f8151f7c9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'hashed_password')
    # ### end Alembic commands ###
