"""fiche produit description et bienfaits

Revision ID: 363bead0aa96
Revises: 58abdded159b
Create Date: 2026-07-22 15:49:42.782247

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '363bead0aa96'
down_revision: str | None = '58abdded159b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default : les produits existants démarrent avec une fiche vide
    op.add_column('products', sa.Column('description', sa.Text(), nullable=False, server_default=''))
    op.add_column('products', sa.Column('benefits', sa.Text(), nullable=False, server_default=''))
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_column('products', 'benefits')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
