"""premiere connexion fournisseur

Revision ID: 36d81901203d
Revises: 0d684c418783
Create Date: 2026-07-17 17:42:21.814674

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '36d81901203d'
down_revision: str | None = '0d684c418783'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default : permet la migration de tables déjà peuplées
    op.add_column(
        'suppliers',
        sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'must_change_password')
    # ### end Alembic commands ###
