"""composition du catalogue

Revision ID: 58abdded159b
Revises: 36d81901203d
Create Date: 2026-07-22 12:52:54.461538

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '58abdded159b'
down_revision: str | None = '36d81901203d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default : les produits déjà référencés entrent par défaut dans le catalogue
    op.add_column('products', sa.Column('in_catalogue', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('products', sa.Column('catalogue_position', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'catalogue_position')
    op.drop_column('products', 'in_catalogue')
    # ### end Alembic commands ###
