"""vitrine produits et profil fournisseur

Revision ID: 84f8151f7c9e
Revises: ca4ee06e2d6f
Create Date: 2026-07-17 12:15:17.328730

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '84f8151f7c9e'
down_revision: str | None = 'ca4ee06e2d6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default : permet la migration de tables déjà peuplées
    op.add_column('products', sa.Column('moq', sa.String(length=50), nullable=False, server_default=''))
    op.add_column('products', sa.Column('image', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('products', sa.Column('visible', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('products', sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('suppliers', sa.Column('categories', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('suppliers', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'last_login_at')
    op.drop_column('suppliers', 'categories')
    op.drop_column('products', 'featured')
    op.drop_column('products', 'visible')
    op.drop_column('products', 'image')
    op.drop_column('products', 'moq')
    # ### end Alembic commands ###
