/** Textes bilingues (FR/EN) du back-office admin.
 *  `useAdminText()` renvoie le dictionnaire de la langue courante (lib/i18n).
 *  Les valeurs enregistrées (statuts, catégories…) restent en français : leur affichage
 *  passe par `useOptionLabel()` (lib/formsText).
 *  Les dictionnaires `fr` et `en` DOIVENT avoir exactement la même forme.
 */

import { useLang, type Lang } from "@/lib/i18n";

const s = (n: number) => (n > 1 ? "s" : "");

const fr = {
  common: {
    loading: "Chargement…",
    cancel: "Annuler",
    save: "Enregistrer",
    saved: "Enregistré",
    close: "Fermer",
    remove: "Retirer",
    add: "Ajouter",
    restore: "Restaurer",
    delete: "Supprimer",
    exportCsv: "Exporter CSV",
    details: "Détails",
    select: "Sélectionner…",
    yes: "Oui",
    no: "Non",
    sending: "Envoi…",
    sendingLong: "Envoi en cours…",
    send: "Envoyer",
    choosePhoto: "Choisir une photo",
    removePhoto: "Retirer la photo",
    photoFormats: "JPG, PNG ou WebP · 5 Mo maximum.",
    uploadError: "Téléversement impossible.",
    tempPassword: "Mot de passe temporaire :",
    tempPasswordNote: "Transmettez ce mot de passe de façon sécurisée · il ne sera plus affiché.",
  },
  shell: {
    nav: {
      dashboard: ["Tableau de bord", "Vue globale"],
      leads: ["Leads & demandes", "Demandes clients"],
      catalogue: ["Catalogue", "Produits, stocks & PDF"],
      fournisseurs: ["Fournisseurs", "Comptes & propositions"],
      rdv: ["Rendez-vous", "Échanges avec l'experte"],
    },
    administrator: "Administrateur",
    logout: "Se déconnecter",
    notifications: "Notifications",
    allRead: "Toutes les notifications sont lues.",
    none: "Aucune notification.",
    newLeads: "Nouveaux leads",
    proposals: "Propositions fournisseurs",
    by: (name: string) => `par ${name}`,
    stockAlerts: "Alertes stock",
    outOfStock: "Rupture de stock",
    staleData: "Données non actualisées",
    markAllRead: "Marquer tout comme lu",
    backToSite: "Retour au site",
  },
  alerts: { overdue: "En retard", followup: "À relancer" },
  dashboard: {
    hello: "Bonjour 👋",
    intro: "Voici un résumé de l'activité de votre plateforme.",
    totalLeads: "Leads totaux",
    totalLeadsSub: (n: number, p: number) => `${n} nouveaux · ${p} en cours`,
    newLeads: "Nouveaux leads",
    awaiting: "en attente de traitement",
    visibleProducts: "Produits visibles",
    featuredSub: (n: number) => `${n} en vedette sur l'accueil`,
    activeSuppliers: "Fournisseurs actifs",
    disabledSub: (n: number) => `${n} désactivé${s(n)}`,
    allActive: "tous actifs",
    stockAlerts: "Alertes stocks",
    staleSub: "données non actualisées",
    ruptures: "Ruptures",
    rupturesSub: "produits à zéro",
    featured: "En vedette",
    featuredSlots: "slots d'accueil utilisés",
    proposals: "Propositions fournisseurs",
    proposalsSub: "en attente de validation",
    recentLeads: "Derniers leads reçus",
    seeAll: "Voir tout →",
    quickAccess: "Accès rapide",
  },
  rdv: {
    title: "Rendez-vous",
    total: "Total réservations", totalSub: "depuis le lancement",
    upcoming: "À venir", upcomingSub: "rendez-vous confirmés",
    confirmed: "Confirmés", confirmedSub: "toutes dates",
    cancelled: "Annulés", cancelledSub: "créneaux libérés",
    headers: ["Date", "Heure", "Durée", "Contact", "Société", "E-mail", "Motif", "Statut", ""],
    loading: "Chargement des rendez-vous…",
    empty: "Aucun rendez-vous réservé pour le moment.",
    cancel: "Annuler",
    reconfirm: "Reconfirmer",
    note: "L'annulation d'un rendez-vous libère immédiatement le créneau à la réservation.",
  },
  leads: {
    title: "Leads & demandes",
    total: "Total leads", totalSub: "toutes catégories",
    newOnes: "Nouveaux", newSub: "en attente de traitement",
    inProgress: "En cours", inProgressSub: "traitement en cours",
    processed: "Traités", processedSub: "cette période",
    tabs: { catalogue: "Catalogue", devis: "Devis", sourcing: "Sourcing", candidatures: "Candidatures fournisseurs" },
    search: "Société, contact, pays…",
    list: "Liste",
    pipeline: "Pipeline",
    all: "Tous",
    loading: "Chargement des leads…",
    empty: "Aucun lead pour ce filtre.",
    reply: {
      catalogue: "Répondre par e-mail",
      devis: "Répondre / envoyer le devis",
      sourcing: "Répondre au sourcing",
      candidatures: "Répondre au candidat",
    },
    contact: "Contact",
    email: "E-mail",
    country: "Pays",
    request: "Demande",
    requestDetails: "Détails de la demande",
    fields: {
      product_types: "Catégories",
      products_offered: "Produits proposés",
      products_requested: "Produits demandés",
      sector: "Domaine d'activité",
      origin: "Provenance souhaitée",
      volume: "Volume / quantité",
      forecast: "Besoin prévisionnel",
      packaging: "Conditionnement",
      incoterm: "Incoterm",
      quality_level: "Niveau de qualité",
      budget: "Budget",
      certifications: "Certifications",
      delivery_delay: "Délai souhaité",
      transport_needed: "Transport organisé par nous",
      delivery_continent: "Destination",
      delivery_place: "Lieu de livraison",
      delivery_contact: "Contact sur place",
      other_need: "Autre besoin",
      language: "Langue du client",
    },
    languageNames: { fr: "Français", en: "Anglais" },
    advance: "Faire avancer",
    changeStatus: "Changer le statut",
    createAccount: "Créer le compte fournisseur",
    accountCreated: (email: string) => `Compte créé · identifiant : ${email}`,
    accountExists: "Un compte fournisseur existe déjà avec cet e-mail.",
    accountNote: "Transmettez-le de façon sécurisée · il ne sera plus affiché. Le fournisseur pourra le changer à sa première connexion.",
    deleteLead: "Supprimer ce lead (RGPD)",
    confirmDeleteTitle: (company: string) => `Supprimer définitivement le lead « ${company} » ?`,
    confirmDeleteMessage: "Cette action est irréversible (RGPD).",
    deleted: "Lead supprimé.",
    dropHere: "Déposer ici",
  },
  replyModal: {
    title: "Répondre par e-mail",
    to: (contact: string, company: string) => `à ${contact} · ${company}`,
    recipient: "Destinataire",
    subject: "Objet",
    message: "Message",
    attachments: "Pièces jointes",
    files: (n: number, size: string) => `${n} fichier${s(n)} · ${size}`,
    attach: "Joindre un fichier (devis, fiche technique…)",
    maxTotal: "15 Mo maximum au total.",
    tooBig: "Pièces jointes trop volumineuses (15 Mo maximum au total).",
    required: "Objet et message sont requis.",
    failed: "Échec de l'envoi. Réessayez.",
    sent: (email: string, n: number) => `E-mail envoyé à ${email}.${n ? ` (${n} pièce${s(n)} jointe${s(n)})` : ""}`,
    units: ["o", "Ko", "Mo"],
    clientLanguage: (lang: string) => `Modèle rédigé dans la langue du client (${lang}).`,
  },
  suppliers: {
    title: "Fournisseurs",
    create: "Créer un compte fournisseur",
    pendingProposals: (n: number) => `${n} proposition${s(n)} en attente de validation`,
    actionRequired: "Action requise",
    viewSheet: "Voir la fiche",
    proposedBy: "Proposé par",
    approve: "Valider",
    refuse: "Refuser",
    proposalTitle: "Proposition de produit",
    noPhoto: "Aucune photo fournie",
    proposalFields: {
      category: "Catégorie", origin: "Origine", packaging: "Conditionnement", moq: "MOQ",
      volumes: "Volumes", price_per_kg: "Prix au kilo", bulk_price: "Prix en vrac", harvest_period: "Période de récolte",
    },
    description: "Description",
    benefits: "Bienfaits",
    certifications: "Certifications",
    approveCreate: "Valider · créer le produit",
    refuseTitle: "Refuser la proposition",
    refuseReason: "Motif du refus (envoyé au fournisseur)",
    refusePlaceholder: "Ex : photos manquantes, certification à fournir, produit hors périmètre…",
    refuseNote: "Le fournisseur recevra ce motif par e-mail · il pourra soumettre une nouvelle proposition ajustée.",
    refuseSubmit: "Refuser et envoyer le motif",
    approved: (name: string) => `Proposition « ${name} » validée · le fournisseur a été informé par e-mail. Un produit masqué a été créé, complétez sa fiche dans Catalogue & stocks.`,
    refused: (name: string) => `Proposition « ${name} » refusée · le fournisseur a été informé par e-mail du motif.`,
    kpiTotal: "Total fournisseurs", kpiTotalSub: "comptes créés",
    kpiActive: "Actifs", kpiActiveSub: "accès activé",
    kpiDisabled: "Désactivés", kpiDisabledSub: "accès suspendu",
    kpiProducts: "Produits référencés", kpiProductsSub: "au total",
    newAccount: "Nouveau compte fournisseur",
    companyName: "Nom de la société *",
    country: "Pays",
    loginEmail: "E-mail de connexion *",
    contactName: "Nom du contact",
    categories: "Catégories de produits",
    accountLanguage: "Langue du fournisseur (espace et e-mails)",
    createNote: "Un mot de passe temporaire sera généré automatiquement et devra être transmis au fournisseur (il lui est aussi envoyé par e-mail). Il se connecte ensuite avec son e-mail et ce mot de passe.",
    note: "Note :",
    createSubmit: "Créer le compte & générer le mot de passe",
    nameEmailRequired: "Nom et e-mail sont requis.",
    emailTaken: "Cet e-mail est déjà référencé.",
    created: (name: string, email: string) => `Compte créé pour ${name} · identifiant : ${email}`,
    passwordReset: (name: string, email: string) => `Mot de passe réinitialisé pour ${name} · identifiant : ${email}`,
    headers: ["Fournisseur", "Pays", "Catégories", "Produits", "Dernière connexion", "Statut", ""],
    loading: "Chargement des fournisseurs…",
    internalRating: "Évaluation interne",
    inStockRate: (n: number) => `${n}% en stock`,
    detentionTitle: "Taux de détention (en stock / actifs)",
    active: "Actif",
    disabled: "Désactivé",
    activate: "Activer",
    deactivate: "Désactiver",
    edit: {
      company: "Société", contact: "Contact", phone: "Téléphone", city: "Ville", country: "Pays", categories: "Catégories",
    },
    rows: {
      country: "Pays", email: "E-mail", contact: "Contact", phone: "Téléphone", city: "Ville",
      createdOn: "Créé le", lastLogin: "Dernière connexion", products: "Produits référencés",
      detention: "Taux de détention", language: "Langue",
    },
    detentionValue: (rate: number, inStock: number) => `${rate} % (${inStock} en stock)`,
    editInfo: "Modifier les informations",
    deactivateAccount: "Désactiver le compte",
    activateAccount: "Activer le compte",
    resetPassword: "Réinitialiser le mot de passe",
  },
  rating: {
    criteria: { credibilite: "Crédibilité", delais: "Respect des délais", retours: "Retours clients" } as Record<string, string>,
    placeholder: "Commentaire interne (facultatif)…",
    ratedOn: (date: string) => `Évalué le ${date}`,
    notRated: "Non évalué",
  },
  catalogue: {
    title: "Catalogue",
    addProduct: "Ajouter un produit",
    kpiProducts: "Produits", kpiProductsSub: (n: number) => `${n} en vedette`,
    kpiFeatured: "En vedette", kpiFeaturedSub: "slots page d'accueil",
    kpiStocks: "Stocks suivis", kpiStocksSub: (n: number) => (n > 0 ? `${n} rupture(s)` : "aucune rupture"),
    kpiAlerts: "Alertes", kpiAlertsSub: "données non actualisées",
    tabs: {
      produits: "Produits & vitrine", stocks: "Stocks & alertes", pdf: "Catalogue PDF",
      demandes: "Demandes de catalogue", archives: "Corbeille",
    },
    trashIntro: "Les produits archivés ne sont plus sur le site ni dans le catalogue, mais restent conservés.",
    trashRestore: " Restaurez-les",
    trashIntroEnd: " à tout moment, ou supprimez-les définitivement.",
    trashEmpty: "La corbeille est vide.",
    searchProducts: "Nom, réf, fournisseur…",
    searchStocks: "Produit, référence…",
    allCategories: "Toutes",
    allCountries: "Tous les pays",
    filterOrigin: "Filtrer par pays d'origine",
    featuredBadge: "★ Vedette",
    editSheet: "Modifier la fiche",
    unfeature: "Retirer de la vedette (accueil)",
    maxFeatured: "Maximum 6 en vedette",
    feature: "Mettre en vedette sur l'accueil",
    trash: "Mettre à la corbeille (réversible)",
    confirmTrashTitle: (name: string) => `Mettre « ${name} » à la corbeille ?`,
    confirmTrashMessage: "Il quitte le site et le catalogue, mais reste restaurable depuis l'onglet « Corbeille ».",
    confirmTrashLabel: "Mettre à la corbeille",
    trashed: "Produit mis à la corbeille.",
    confirmPurgeTitle: (name: string) => `Supprimer définitivement « ${name} » ?`,
    confirmPurgeMessage: "Cette action est irréversible.",
    confirmPurgeLabel: "Supprimer définitivement",
    purged: "Produit supprimé définitivement.",
    nameRequired: "Le nom du produit est requis.",
    supplierRequired: "Sélectionnez un fournisseur.",
    refTaken: "Cette référence est déjà utilisée.",
    staleWarning: (n: number) => `${n} référence${s(n)} sans mise à jour depuis plus de 14 jours`,
    notUpdated: "Non actualisé",
    remindTitle: (name: string) => `Relancer ${name} par e-mail`,
    remind: "Relancer",
    reminded: (name: string, n: number) => `Relance envoyée à ${name} (${n} référence${s(n)}).`,
    nothingToRemind: "Aucune référence à relancer pour ce fournisseur.",
    updated: (date: string) => `Màj ${date}`,
  },
  composition: {
    loading: "Chargement du catalogue…",
    contains: (n: number) => `Votre catalogue contient ${n} produit${s(n)}`,
    pages: (n: number) => `Environ ${n} pages · couverture, présentation et contacts inclus`,
    generated: (lang: Lang) => `Catalogue PDF (${lang === "fr" ? "français" : "anglais"}) généré · le téléchargement a démarré.`,
    inCatalogue: "Dans le catalogue",
    dragHint: "Attrapez une ligne et faites-la glisser pour changer l'ordre des pages",
    emptyIn: "Aucun produit dans le catalogue. Ajoutez-en depuis la liste ci-dessous.",
    outTitle: "Pas dans le catalogue",
    outIntro: "Ces produits existent au référentiel mais n'apparaissent pas dans le PDF. Cliquez sur « Ajouter » pour les y faire entrer.",
    allIn: "Tous vos produits figurent dans le catalogue.",
    added: (name: string) => `« ${name} » ajouté au catalogue.`,
    removed: (name: string) => `« ${name} » retiré du catalogue.`,
  },
  requests: {
    intro: "Chaque personne qui remplit le formulaire reçoit le catalogue ",
    introStrong: "automatiquement par e-mail",
    introEnd: ". Utilisez « Renvoyer » pour lui adresser à nouveau la dernière édition.",
    headers: ["Date", "Demandeur", "Société", "E-mail", "Pays", "Statut", "Téléchargé", ""],
    empty: "Aucune demande de catalogue pour le moment.",
    downloads: (n: number) => `${n} téléchargement(s)`,
    notYet: "Pas encore",
    resend: "Renvoyer",
    sendTitle: "Envoyer le catalogue",
    from: "De", to: "À", subject: "Objet",
    linkNote: "Lien de téléchargement sécurisé, valable 24 h · il contient toujours la dernière édition du catalogue.",
    resent: (email: string) => `Catalogue renvoyé à ${email}.`,
  },
  productForm: {
    editTitle: "Modifier la fiche produit",
    newTitle: "Nouvelle fiche produit",
    photo: "Photo du produit",
    name: "Nom du produit *",
    ref: "Référence",
    delay: "Délai indicatif",
    category: "Catégorie",
    origin: "Origine (pays)",
    supplier: "Fournisseur *",
    stock: "Stock (kg)",
    availability: "Disponibilité",
    description: "Description",
    descriptionPlaceholder: "Ce qu'est le produit, sa provenance, son usage…",
    benefits: "Bienfaits",
    benefitsPlaceholder: "Apports nutritionnels, atouts pour l'acheteur…",
    internal: "Prix & récolte · internes",
    pricePerKg: "Prix au kilo",
    bulkPrice: "Prix en vrac",
    harvest: "Période de récolte",
    saveEdit: "Enregistrer les modifications",
    create: "Créer le produit",
  },
};

const en: typeof fr = {
  common: {
    loading: "Loading…",
    cancel: "Cancel",
    save: "Save",
    saved: "Saved",
    close: "Close",
    remove: "Remove",
    add: "Add",
    restore: "Restore",
    delete: "Delete",
    exportCsv: "Export CSV",
    details: "Details",
    select: "Select…",
    yes: "Yes",
    no: "No",
    sending: "Sending…",
    sendingLong: "Sending…",
    send: "Send",
    choosePhoto: "Choose a photo",
    removePhoto: "Remove photo",
    photoFormats: "JPG, PNG or WebP · 5 MB maximum.",
    uploadError: "Upload failed.",
    tempPassword: "Temporary password:",
    tempPasswordNote: "Share this password securely · it will not be shown again.",
  },
  shell: {
    nav: {
      dashboard: ["Dashboard", "Overview"],
      leads: ["Leads & requests", "Client requests"],
      catalogue: ["Catalogue", "Products, stock & PDF"],
      fournisseurs: ["Suppliers", "Accounts & proposals"],
      rdv: ["Appointments", "Calls with the expert"],
    },
    administrator: "Administrator",
    logout: "Sign out",
    notifications: "Notifications",
    allRead: "All notifications have been read.",
    none: "No notifications.",
    newLeads: "New leads",
    proposals: "Supplier proposals",
    by: (name) => `by ${name}`,
    stockAlerts: "Stock alerts",
    outOfStock: "Out of stock",
    staleData: "Data not updated",
    markAllRead: "Mark all as read",
    backToSite: "Back to website",
  },
  alerts: { overdue: "Overdue", followup: "Follow up" },
  dashboard: {
    hello: "Hello 👋",
    intro: "Here is a summary of your platform's activity.",
    totalLeads: "Total leads",
    totalLeadsSub: (n, p) => `${n} new · ${p} in progress`,
    newLeads: "New leads",
    awaiting: "awaiting processing",
    visibleProducts: "Visible products",
    featuredSub: (n) => `${n} featured on the home page`,
    activeSuppliers: "Active suppliers",
    disabledSub: (n) => `${n} disabled`,
    allActive: "all active",
    stockAlerts: "Stock alerts",
    staleSub: "data not updated",
    ruptures: "Out of stock",
    rupturesSub: "products at zero",
    featured: "Featured",
    featuredSlots: "home page slots used",
    proposals: "Supplier proposals",
    proposalsSub: "awaiting review",
    recentLeads: "Latest leads",
    seeAll: "See all →",
    quickAccess: "Quick access",
  },
  rdv: {
    title: "Appointments",
    total: "Total bookings", totalSub: "since launch",
    upcoming: "Upcoming", upcomingSub: "confirmed appointments",
    confirmed: "Confirmed", confirmedSub: "all dates",
    cancelled: "Cancelled", cancelledSub: "slots released",
    headers: ["Date", "Time", "Duration", "Contact", "Company", "Email", "Purpose", "Status", ""],
    loading: "Loading appointments…",
    empty: "No appointment booked yet.",
    cancel: "Cancel",
    reconfirm: "Reconfirm",
    note: "Cancelling an appointment immediately makes the slot available for booking again.",
  },
  leads: {
    title: "Leads & requests",
    total: "Total leads", totalSub: "all categories",
    newOnes: "New", newSub: "awaiting processing",
    inProgress: "In progress", inProgressSub: "being processed",
    processed: "Processed", processedSub: "this period",
    tabs: { catalogue: "Catalogue", devis: "Quotes", sourcing: "Sourcing", candidatures: "Supplier applications" },
    search: "Company, contact, country…",
    list: "List",
    pipeline: "Pipeline",
    all: "All",
    loading: "Loading leads…",
    empty: "No lead for this filter.",
    reply: {
      catalogue: "Reply by email",
      devis: "Reply / send the quote",
      sourcing: "Reply to the sourcing request",
      candidatures: "Reply to the applicant",
    },
    contact: "Contact",
    email: "Email",
    country: "Country",
    request: "Request",
    requestDetails: "Request details",
    fields: {
      product_types: "Categories",
      products_offered: "Products offered",
      products_requested: "Products requested",
      sector: "Business sector",
      origin: "Preferred origin",
      volume: "Volume / quantity",
      forecast: "Forecast needs",
      packaging: "Packaging",
      incoterm: "Incoterm",
      quality_level: "Quality level",
      budget: "Budget",
      certifications: "Certifications",
      delivery_delay: "Desired lead time",
      transport_needed: "Transport arranged by us",
      delivery_continent: "Destination",
      delivery_place: "Delivery place",
      delivery_contact: "On-site contact",
      other_need: "Other needs",
      language: "Client language",
    },
    languageNames: { fr: "French", en: "English" },
    advance: "Move forward",
    changeStatus: "Change status",
    createAccount: "Create the supplier account",
    accountCreated: (email) => `Account created · login: ${email}`,
    accountExists: "A supplier account already exists with this email.",
    accountNote: "Share it securely · it will not be shown again. The supplier can change it at first sign-in.",
    deleteLead: "Delete this lead (GDPR)",
    confirmDeleteTitle: (company) => `Permanently delete the lead "${company}"?`,
    confirmDeleteMessage: "This action cannot be undone (GDPR).",
    deleted: "Lead deleted.",
    dropHere: "Drop here",
  },
  replyModal: {
    title: "Reply by email",
    to: (contact, company) => `to ${contact} · ${company}`,
    recipient: "Recipient",
    subject: "Subject",
    message: "Message",
    attachments: "Attachments",
    files: (n, size) => `${n} file${s(n)} · ${size}`,
    attach: "Attach a file (quote, technical sheet…)",
    maxTotal: "15 MB maximum in total.",
    tooBig: "Attachments too large (15 MB maximum in total).",
    required: "Subject and message are required.",
    failed: "Sending failed. Please try again.",
    sent: (email, n) => `Email sent to ${email}.${n ? ` (${n} attachment${s(n)})` : ""}`,
    units: ["B", "KB", "MB"],
    clientLanguage: (lang) => `Template written in the client's language (${lang}).`,
  },
  suppliers: {
    title: "Suppliers",
    create: "Create a supplier account",
    pendingProposals: (n) => `${n} proposal${s(n)} awaiting review`,
    actionRequired: "Action required",
    viewSheet: "View sheet",
    proposedBy: "Proposed by",
    approve: "Approve",
    refuse: "Reject",
    proposalTitle: "Product proposal",
    noPhoto: "No photo provided",
    proposalFields: {
      category: "Category", origin: "Origin", packaging: "Packaging", moq: "MOQ",
      volumes: "Volumes", price_per_kg: "Price per kg", bulk_price: "Bulk price", harvest_period: "Harvest period",
    },
    description: "Description",
    benefits: "Benefits",
    certifications: "Certifications",
    approveCreate: "Approve · create the product",
    refuseTitle: "Reject the proposal",
    refuseReason: "Reason for rejection (sent to the supplier)",
    refusePlaceholder: "e.g. missing photos, certification required, product out of scope…",
    refuseNote: "The supplier will receive this reason by email · they can submit an adjusted proposal.",
    refuseSubmit: "Reject and send the reason",
    approved: (name) => `Proposal "${name}" approved · the supplier has been notified by email. A hidden product has been created; complete its sheet in Catalogue & stock.`,
    refused: (name) => `Proposal "${name}" rejected · the supplier has been notified of the reason by email.`,
    kpiTotal: "Total suppliers", kpiTotalSub: "accounts created",
    kpiActive: "Active", kpiActiveSub: "access enabled",
    kpiDisabled: "Disabled", kpiDisabledSub: "access suspended",
    kpiProducts: "Listed products", kpiProductsSub: "in total",
    newAccount: "New supplier account",
    companyName: "Company name *",
    country: "Country",
    loginEmail: "Login email *",
    contactName: "Contact name",
    categories: "Product categories",
    accountLanguage: "Supplier language (area and emails)",
    createNote: "A temporary password will be generated automatically and must be shared with the supplier (it is also sent by email). They then sign in with their email and this password.",
    note: "Note:",
    createSubmit: "Create the account & generate the password",
    nameEmailRequired: "Name and email are required.",
    emailTaken: "This email is already registered.",
    created: (name, email) => `Account created for ${name} · login: ${email}`,
    passwordReset: (name, email) => `Password reset for ${name} · login: ${email}`,
    headers: ["Supplier", "Country", "Categories", "Products", "Last sign-in", "Status", ""],
    loading: "Loading suppliers…",
    internalRating: "Internal rating",
    inStockRate: (n) => `${n}% in stock`,
    detentionTitle: "In-stock rate (in stock / active)",
    active: "Active",
    disabled: "Disabled",
    activate: "Enable",
    deactivate: "Disable",
    edit: {
      company: "Company", contact: "Contact", phone: "Phone", city: "City", country: "Country", categories: "Categories",
    },
    rows: {
      country: "Country", email: "Email", contact: "Contact", phone: "Phone", city: "City",
      createdOn: "Created on", lastLogin: "Last sign-in", products: "Listed products",
      detention: "In-stock rate", language: "Language",
    },
    detentionValue: (rate, inStock) => `${rate}% (${inStock} in stock)`,
    editInfo: "Edit information",
    deactivateAccount: "Disable the account",
    activateAccount: "Enable the account",
    resetPassword: "Reset the password",
  },
  rating: {
    criteria: { credibilite: "Credibility", delais: "On-time delivery", retours: "Customer feedback" },
    placeholder: "Internal comment (optional)…",
    ratedOn: (date) => `Rated on ${date}`,
    notRated: "Not rated",
  },
  catalogue: {
    title: "Catalogue",
    addProduct: "Add a product",
    kpiProducts: "Products", kpiProductsSub: (n) => `${n} featured`,
    kpiFeatured: "Featured", kpiFeaturedSub: "home page slots",
    kpiStocks: "Tracked stock", kpiStocksSub: (n) => (n > 0 ? `${n} out of stock` : "none out of stock"),
    kpiAlerts: "Alerts", kpiAlertsSub: "data not updated",
    tabs: {
      produits: "Products & showcase", stocks: "Stock & alerts", pdf: "PDF catalogue",
      demandes: "Catalogue requests", archives: "Trash",
    },
    trashIntro: "Archived products are no longer on the site or in the catalogue, but they are kept.",
    trashRestore: " Restore them",
    trashIntroEnd: " at any time, or delete them permanently.",
    trashEmpty: "The trash is empty.",
    searchProducts: "Name, ref, supplier…",
    searchStocks: "Product, reference…",
    allCategories: "All",
    allCountries: "All countries",
    filterOrigin: "Filter by country of origin",
    featuredBadge: "★ Featured",
    editSheet: "Edit product sheet",
    unfeature: "Remove from featured (home page)",
    maxFeatured: "Maximum 6 featured",
    feature: "Feature on the home page",
    trash: "Move to trash (reversible)",
    confirmTrashTitle: (name) => `Move "${name}" to the trash?`,
    confirmTrashMessage: "It leaves the site and the catalogue, but can be restored from the \"Trash\" tab.",
    confirmTrashLabel: "Move to trash",
    trashed: "Product moved to the trash.",
    confirmPurgeTitle: (name) => `Permanently delete "${name}"?`,
    confirmPurgeMessage: "This action cannot be undone.",
    confirmPurgeLabel: "Delete permanently",
    purged: "Product permanently deleted.",
    nameRequired: "The product name is required.",
    supplierRequired: "Select a supplier.",
    refTaken: "This reference is already in use.",
    staleWarning: (n) => `${n} product${s(n)} not updated for more than 14 days`,
    notUpdated: "Not updated",
    remindTitle: (name) => `Send ${name} a reminder by email`,
    remind: "Remind",
    reminded: (name, n) => `Reminder sent to ${name} (${n} product${s(n)}).`,
    nothingToRemind: "Nothing to remind this supplier about.",
    updated: (date) => `Updated ${date}`,
  },
  composition: {
    loading: "Loading the catalogue…",
    contains: (n) => `Your catalogue contains ${n} product${s(n)}`,
    pages: (n) => `About ${n} pages · cover, introduction and contacts included`,
    generated: (lang) => `PDF catalogue (${lang === "fr" ? "French" : "English"}) generated · the download has started.`,
    inCatalogue: "In the catalogue",
    dragHint: "Grab a row and drag it to change the page order",
    emptyIn: "No product in the catalogue. Add some from the list below.",
    outTitle: "Not in the catalogue",
    outIntro: "These products exist in the product list but do not appear in the PDF. Click \"Add\" to include them.",
    allIn: "All your products are in the catalogue.",
    added: (name) => `"${name}" added to the catalogue.`,
    removed: (name) => `"${name}" removed from the catalogue.`,
  },
  requests: {
    intro: "Everyone who fills in the form receives the catalogue ",
    introStrong: "automatically by email",
    introEnd: ". Use \"Resend\" to send them the latest edition again.",
    headers: ["Date", "Requester", "Company", "Email", "Country", "Status", "Downloaded", ""],
    empty: "No catalogue request yet.",
    downloads: (n) => `${n} download(s)`,
    notYet: "Not yet",
    resend: "Resend",
    sendTitle: "Send the catalogue",
    from: "From", to: "To", subject: "Subject",
    linkNote: "Secure download link, valid for 24 h · it always contains the latest edition of the catalogue.",
    resent: (email) => `Catalogue resent to ${email}.`,
  },
  productForm: {
    editTitle: "Edit product sheet",
    newTitle: "New product sheet",
    photo: "Product photo",
    name: "Product name *",
    ref: "Reference",
    delay: "Indicative lead time",
    category: "Category",
    origin: "Origin (country)",
    supplier: "Supplier *",
    stock: "Stock (kg)",
    availability: "Availability",
    description: "Description",
    descriptionPlaceholder: "What the product is, where it comes from, how it is used…",
    benefits: "Benefits",
    benefitsPlaceholder: "Nutritional value, advantages for the buyer…",
    internal: "Price & harvest · internal",
    pricePerKg: "Price per kg",
    bulkPrice: "Bulk price",
    harvest: "Harvest period",
    saveEdit: "Save changes",
    create: "Create the product",
  },
};

export const ADMIN_TEXT: Record<Lang, typeof fr> = { fr, en };
export const useAdminText = () => ADMIN_TEXT[useLang()];

// ─── Modèles d'e-mail envoyés aux clients : dans la langue DU CLIENT ─────────

type ReplyTab = "catalogue" | "devis" | "sourcing" | "candidatures";

/** Objet + message pré-remplis pour répondre à un lead, dans la langue du client. */
export function replyTemplate(lang: Lang, tab: ReplyTab, firstName: string, product?: string): { subject: string; body: string } {
  if (lang === "en") {
    const about = product ? ` regarding ${product}` : "";
    const subject = tab === "devis" ? "Your quotation request · Funti"
      : tab === "sourcing" ? "Your sourcing request · Funti"
      : tab === "candidatures" ? "Your supplier application · Funti"
      : "Your request · Funti";
    const intro = tab === "devis" ? `Thank you for your quotation request${about}.`
      : tab === "sourcing" ? `Thank you for your sourcing request${about}.`
      : tab === "candidatures" ? "Thank you for your application."
      : "Thank you for your request.";
    const middle = tab === "devis" ? "[Detail your proposal here · products, price, logistics, Incoterm.]"
      : "[Detail your answer here.]";
    return { subject, body: `Hello ${firstName},\n\n${intro}\n\n${middle}\n\nKind regards,\nThe Funti team` };
  }
  const about = product ? ` concernant ${product}` : "";
  const subject = tab === "devis" ? "Votre demande de cotation · Funti"
    : tab === "sourcing" ? "Votre demande de sourcing · Funti"
    : tab === "candidatures" ? "Votre candidature fournisseur · Funti"
    : "Votre demande · Funti";
  const intro = tab === "devis" ? `Merci pour votre demande de cotation${about}.`
    : tab === "sourcing" ? `Merci pour votre demande de sourcing${about}.`
    : tab === "candidatures" ? "Merci pour votre candidature."
    : "Merci pour votre demande.";
  const middle = tab === "devis" ? "[Détaillez ici votre proposition · produits, prix, logistique, incoterm.]"
    : "[Détaillez ici votre réponse.]";
  return { subject, body: `Bonjour ${firstName},\n\n${intro}\n\n${middle}\n\nBien cordialement,\nL'équipe Funti` };
}

/** Aperçu de l'e-mail du catalogue tel que le client le reçoit (langue du client). */
export const CATALOGUE_EMAIL: Record<Lang, { subject: string; hello: (n: string) => string; body: string; link: string; signature: string }> = {
  fr: {
    subject: "Votre catalogue Funti",
    hello: (n) => `Bonjour ${n},`,
    body: "Merci pour votre intérêt. Votre catalogue est disponible via le lien ci-dessous.",
    link: "Télécharger le catalogue Funti",
    signature: "L'équipe Funti",
  },
  en: {
    subject: "Your Funti catalogue",
    hello: (n) => `Hello ${n},`,
    body: "Thank you for your interest. Your catalogue is available via the link below.",
    link: "Download the Funti catalogue",
    signature: "The Funti team",
  },
};
