/** Textes bilingues (FR/EN) du parcours client : catalogue, fiche produit, devis,
 *  sourcing, candidature fournisseur, rendez-vous et écrans de confirmation.
 *
 *  - `useFormsText()` renvoie le dictionnaire de la langue courante (lib/i18n).
 *  - `useOptionLabel()` traduit l'AFFICHAGE d'une valeur de liste fixe (secteur, délai,
 *    pays…) : la valeur envoyée au serveur reste en français, pour des données homogènes
 *    côté admin.
 *  Les dictionnaires `fr` et `en` DOIVENT avoir exactement la même forme.
 */

import { useCallback } from "react";
import { useLang, type Lang } from "@/lib/i18n";

const fr = {
  common: {
    back: "Retour",
    prev: "Précédent",
    next: "Suivant",
    send: "Envoyer",
    sending: "Envoi…",
    sendingLong: "Envoi en cours…",
    step: (n: number, total: number) => `Étape ${n} / ${total}`,
    select: "Sélectionner",
    other: "Autre",
    specify: "Préciser…",
    countrySearch: "Rechercher un pays…",
    addTag: "+ ajouter…",
    yes: "Oui",
    no: "Non",
    genericError: "Une erreur est survenue. Réessayez.",
    confirmation: "Confirmation",
    backHome: "Retour à l'accueil",
    rgpd: "J'accepte que mes coordonnées soient utilisées par Funti pour me transmettre le catalogue et me recontacter au sujet de ma demande.",
    privacy: "Politique de confidentialité.",
    rgpdFoot: "Vos données sont traitées de manière confidentielle (RGPD). Aucun contact direct avec les fournisseurs.",
    urgent: "Besoin d'une réponse urgente ?",
    bookExpert: "Réserver un créneau avec l'experte",
  },
  company: {
    stepLabel: "Votre entreprise",
    stepHint: "Qui êtes-vous ?",
    required: "Renseignez votre société, votre contact, votre e-mail et votre pays.",
    company: "Société",
    contact: "Contact & fonction",
    email: "E-mail professionnel",
    country: "Pays",
    sector: "Domaine d'activité",
    sectorPlaceholder: "Votre secteur…",
  },
  delivery: {
    stepLabel: "Livraison",
    delay: "Délai de livraison souhaité",
    continent: "La livraison est prévue en",
    place: "Lieu / port de livraison finale",
    placePlaceholder: "Ex. port de Rotterdam",
    onSite: "Contact sur place",
    onSitePlaceholder: "Nom · téléphone",
  },
  incoterm: {
    label: "Incoterm souhaité",
    understand: "Comprendre les incoterms",
    byComfort: "Choisir selon votre confort",
  },
  catalogue: {
    screen: "Télécharger le catalogue",
    title: "Recevez notre catalogue à jour",
    subtitle: "Épicerie, boissons, fruits & légumes, matières premières : parcourez nos références d'origine africaine, dans leur dernière édition. Les prix sont communiqués sur devis, sous 24 à 48 h ouvrées.",
    firstName: "Prénom",
    lastName: "Nom",
    company: "Société",
    companyPlaceholder: "Épicerie du Marché SAS",
    email: "E-mail professionnel",
    emailPlaceholder: "m.dupont@epicerie.fr",
    country: "Pays",
    role: "Fonction",
    rolePlaceholder: "Directeur des achats",
    phone: "Téléphone",
    submit: "Recevoir le catalogue",
    thanks: "Merci !",
    onItsWay: "Votre catalogue est en route · vous le recevrez par e-mail dans quelques instants.",
    download: "Télécharger le catalogue (PDF)",
    immediate: "Besoin d'une réponse immédiate ?",
    book30: "Réserver un échange de 30 min avec l'experte",
  },
  devis: {
    title: "Cotation produit",
    intro: "Décrivez votre besoin en 3 étapes : nous revenons vers vous sous 24 à 48 h avec une proposition complète.",
    submit: "Recevoir ma cotation",
    contactPlaceholder: "Marie Dupont · Responsable achats",
    needLabel: "Votre besoin",
    needHint: "Quels produits ?",
    needRequired: "Indiquez au moins une matière recherchée.",
    materials: "Matières recherchées",
    materialsPlaceholder: "Commencez à écrire · choisissez dans notre catalogue…",
    notInCatalogue: (names: string, plural: boolean) =>
      `${names} ${plural ? "ne figurent" : "ne figure"} pas à notre catalogue · nous ${plural ? "les" : "le"} sourçons pour vous.`,
    goSourcing: "Passer en sourcing sur mesure →",
    absent: "Un produit absent de notre catalogue ? Faites une demande de sourcing sur mesure →",
    volume: "Volume estimé",
    volumePlaceholder: "12 tonnes",
    packaging: "Conditionnement",
    packagingPlaceholder: "Préciser le conditionnement…",
    incoterm: "Incoterm",
    forecast: "Besoin prévisionnel",
    forecastPlaceholder: "Ex. 5 tonnes",
    certs: "Certifications requises",
    deliveryHint: "Où et quand ?",
    weTransport: "Souhaitez-vous que nous organisions le transport ?",
    buyerTransport: "Avec cet incoterm, vous organisez le transport principal · nous n'intervenons pas sur l'acheminement.",
    received: "Demande bien reçue",
    receivedDevis: "Notre équipe vous revient sous 24 à 48 h ouvrées avec une proposition complète · produits, logistique, incoterm.",
    receivedSourcing: "Votre demande de sourcing sur mesure est transmise. Notre équipe vous contacte sous 24 à 48 h ouvrées pour qualifier votre besoin.",
  },
  sourcing: {
    title: "Sourcing sur mesure",
    intro: "Un produit absent du catalogue ? Décrivez-le en 3 étapes : notre équipe le source dans son réseau de 100+ fournisseurs.",
    submit: "Envoyer ma demande",
    contactPlaceholder: "Nom Prénom · Fonction",
    needHint: "Le produit recherché",
    needRequired: "Indiquez le produit souhaité et une description de votre besoin.",
    product: "Produit souhaité",
    productPlaceholder: "Beurre de karité raffiné",
    alreadyInCatalogue: (name: string) => `« ${name} » figure déjà à notre catalogue · vous pouvez obtenir un`,
    quoteDirect: "devis directement →",
    description: "Description du besoin",
    descriptionPlaceholder: "Usage, conditionnement attendu, contraintes particulières…",
    origin: "Pays de provenance souhaité",
    quantity: "Quantité souhaitée",
    quantityPlaceholder: "Ex. 5 000 kg",
    forecastPlaceholder: "Ex. 2 tonnes",
    budget: "Budget estimatif",
    optional: "Facultatif",
    quality: "Niveau de qualité",
    otherNeed: "Autre besoin ?",
    otherNeedPlaceholder: "Toute précision utile : marque, saisonnalité, échantillon souhaité…",
    documents: "Documents (facultatif)",
    documentsHint: "Cahier des charges, fiche technique, photos de référence",
    documentsFormats: "PDF, XLSX, JPG, PNG · 10 Mo max",
    deliveryHint: "Logistique & délai",
    clientLogistics: "La logistique est-elle prise en charge par le client ?",
    buyerTransport: "Avec cet incoterm, le client organise le transport principal · nous n'intervenons pas sur l'acheminement.",
  },
  candidature: {
    screen: "Candidature fournisseur",
    title: "Devenir fournisseur référencé",
    subtitle: "Chaque dossier est étudié avec attention. Notre équipe vous recontacte sous 10 jours ouvrés.",
    company: "Société",
    contactName: "Nom du contact",
    email: "E-mail",
    phone: "Téléphone",
    country: "Pays",
    city: "Ville",
    categories: "Catégories",
    products: "Produits proposés",
    pickCategoryFirst: "Sélectionnez d'abord une ou plusieurs catégories ci-dessus.",
    addProduct: "Ajouter un produit…",
    otherProduct: "Autre (préciser)",
    productName: "Nom du produit",
    add: "Ajouter",
    remove: "Retirer",
    certs: "Certifications détenues",
    photos: "Photos / documents (facultatif)",
    photosHint: "Photos produits, fiches techniques, certifications",
    submit: "Envoyer ma candidature",
    requiredContact: "Merci de renseigner votre société, votre contact, votre e-mail et votre pays.",
    requiredCategory: "Sélectionnez au moins une catégorie.",
    requiredProduct: "Indiquez au moins un produit que vous proposez.",
    received: "Candidature reçue",
    receivedText: "Merci pour votre candidature. Chaque dossier est étudié avec attention : notre équipe vous recontactera sous 10 jours ouvrés pour la suite · échanges, évaluation des produits, audit.",
  },
  rdv: {
    screen: "Réserver un échange avec l'experte",
    title: "Échanger avec Oumou Soumano",
    subtitle: "Experte supply chain & sourcing Afrique · Europe",
    duration: "Durée de l'échange",
    motif: "Motif de l'échange",
    motifPlaceholder: "Sélectionner un motif",
    pickDay: "Choisissez un jour",
    slots: (day: string) => `Créneaux · ${day}`,
    loadingSlots: "Chargement des disponibilités…",
    noSlot: "Aucun créneau disponible ce jour · choisissez un autre jour.",
    timezone: (tz: string) => `Fuseau détecté : ${tz}`,
    yourDetails: "Vos coordonnées",
    name: "Nom",
    company: "Société",
    companyPlaceholder: "Votre société",
    email: "E-mail",
    emailPlaceholder: "vous@entreprise.fr",
    confirming: "Confirmation…",
    confirm: (day: string, slot: string) => `Confirmer · ${day} à ${slot}`,
    slotTaken: "Ce créneau vient d'être réservé · choisissez-en un autre.",
    confirmed: "Rendez-vous confirmé",
    confirmedText: (day: string, slot: string, dur: number) =>
      `Votre échange du ${day} à ${slot} (${dur} min) est confirmé. Vous recevrez par e-mail le lien de visioconférence ainsi que les options d'annulation ou de report.`,
  },
  product: {
    catalogue: "Catalogue",
    screen: "Fiche produit",
    loading: "Chargement…",
    notFound: "Produit introuvable.",
    notFoundText: "Ce produit n'est pas au catalogue · nous pouvons le sourcer pour vous.",
    sourcing: "Sourcing sur mesure",
    verified: "Vérifié",
    priceOnQuote: "Prix sur devis",
    origin: "Origine",
    verifiedSupplier: "Fournisseur vérifié",
    packaging: "Conditionnement",
    moq: "Quantité minimum (MOQ)",
    added: "Ajouté",
    addToRequest: "+ Ajouter à ma demande",
    requestQuote: "Demander un devis",
    protected: "Fournisseur vérifié · identité protégée. Aucun contact direct : Funti porte votre devis de bout en bout.",
    description: "Description",
    benefits: "Bienfaits",
    others: "Autres produits",
    downloadAll: "Télécharger le catalogue complet",
    view: "Voir la fiche",
  },
};

const en: typeof fr = {
  common: {
    back: "Back",
    prev: "Previous",
    next: "Next",
    send: "Send",
    sending: "Sending…",
    sendingLong: "Sending…",
    step: (n, total) => `Step ${n} / ${total}`,
    select: "Select",
    other: "Other",
    specify: "Please specify…",
    countrySearch: "Search for a country…",
    addTag: "+ add…",
    yes: "Yes",
    no: "No",
    genericError: "Something went wrong. Please try again.",
    confirmation: "Confirmation",
    backHome: "Back to home page",
    rgpd: "I agree that Funti may use my details to send me the catalogue and contact me about my request.",
    privacy: "Privacy policy.",
    rgpdFoot: "Your data is handled confidentially (GDPR). No direct contact with suppliers.",
    urgent: "Need an urgent answer?",
    bookExpert: "Book a slot with our expert",
  },
  company: {
    stepLabel: "Your company",
    stepHint: "Who are you?",
    required: "Please enter your company, contact person, email and country.",
    company: "Company",
    contact: "Contact & job title",
    email: "Business email",
    country: "Country",
    sector: "Business sector",
    sectorPlaceholder: "Your sector…",
  },
  delivery: {
    stepLabel: "Delivery",
    delay: "Desired delivery time",
    continent: "Delivery is planned in",
    place: "Final delivery place / port",
    placePlaceholder: "e.g. port of Rotterdam",
    onSite: "On-site contact",
    onSitePlaceholder: "Name · phone",
  },
  incoterm: {
    label: "Preferred Incoterm",
    understand: "Understanding Incoterms",
    byComfort: "Choose by comfort level",
  },
  catalogue: {
    screen: "Download the catalogue",
    title: "Get our latest catalogue",
    subtitle: "Groceries, beverages, fruits & vegetables, raw materials: browse our products of African origin in their latest edition. Prices are provided on quotation, within 24 to 48 business hours.",
    firstName: "First name",
    lastName: "Last name",
    company: "Company",
    companyPlaceholder: "Market Foods Ltd",
    email: "Business email",
    emailPlaceholder: "m.smith@company.com",
    country: "Country",
    role: "Job title",
    rolePlaceholder: "Purchasing manager",
    phone: "Phone",
    submit: "Get the catalogue",
    thanks: "Thank you!",
    onItsWay: "Your catalogue is on its way · you will receive it by email in a few moments.",
    download: "Download the catalogue (PDF)",
    immediate: "Need an immediate answer?",
    book30: "Book a 30-minute call with our expert",
  },
  devis: {
    title: "Product quotation",
    intro: "Describe your needs in 3 steps: we will get back to you within 24 to 48 hours with a complete proposal.",
    submit: "Get my quotation",
    contactPlaceholder: "Mary Smith · Purchasing manager",
    needLabel: "Your needs",
    needHint: "Which products?",
    needRequired: "Please enter at least one product.",
    materials: "Products wanted",
    materialsPlaceholder: "Start typing · choose from our catalogue…",
    notInCatalogue: (names, plural) =>
      `${names} ${plural ? "are" : "is"} not in our catalogue · we will source ${plural ? "them" : "it"} for you.`,
    goSourcing: "Switch to custom sourcing →",
    absent: "A product not in our catalogue? Make a custom sourcing request →",
    volume: "Estimated volume",
    volumePlaceholder: "12 tonnes",
    packaging: "Packaging",
    packagingPlaceholder: "Specify the packaging…",
    incoterm: "Incoterm",
    forecast: "Forecast needs",
    forecastPlaceholder: "e.g. 5 tonnes",
    certs: "Required certifications",
    deliveryHint: "Where and when?",
    weTransport: "Would you like us to arrange transport?",
    buyerTransport: "With this Incoterm, you arrange the main transport · we are not involved in shipping.",
    received: "Request received",
    receivedDevis: "Our team will get back to you within 24 to 48 business hours with a complete proposal · products, logistics, Incoterm.",
    receivedSourcing: "Your custom sourcing request has been sent. Our team will contact you within 24 to 48 business hours to review your needs.",
  },
  sourcing: {
    title: "Custom sourcing",
    intro: "A product not in our catalogue? Describe it in 3 steps: our team will source it through its network of 100+ suppliers.",
    submit: "Send my request",
    contactPlaceholder: "Full name · Job title",
    needHint: "The product you need",
    needRequired: "Please enter the product you need and a description of your needs.",
    product: "Product wanted",
    productPlaceholder: "Refined shea butter",
    alreadyInCatalogue: (name) => `"${name}" is already in our catalogue · you can get a`,
    quoteDirect: "quotation directly →",
    description: "Description of your needs",
    descriptionPlaceholder: "Use, expected packaging, specific constraints…",
    origin: "Preferred country of origin",
    quantity: "Quantity wanted",
    quantityPlaceholder: "e.g. 5,000 kg",
    forecastPlaceholder: "e.g. 2 tonnes",
    budget: "Estimated budget",
    optional: "Optional",
    quality: "Quality level",
    otherNeed: "Anything else?",
    otherNeedPlaceholder: "Any useful detail: brand, seasonality, sample wanted…",
    documents: "Documents (optional)",
    documentsHint: "Specifications, technical sheet, reference photos",
    documentsFormats: "PDF, XLSX, JPG, PNG · 10 MB max",
    deliveryHint: "Logistics & timing",
    clientLogistics: "Does the client handle logistics?",
    buyerTransport: "With this Incoterm, the client arranges the main transport · we are not involved in shipping.",
  },
  candidature: {
    screen: "Supplier application",
    title: "Become a listed supplier",
    subtitle: "Every application is carefully reviewed. Our team will get back to you within 10 business days.",
    company: "Company",
    contactName: "Contact name",
    email: "Email",
    phone: "Phone",
    country: "Country",
    city: "City",
    categories: "Categories",
    products: "Products offered",
    pickCategoryFirst: "First select one or more categories above.",
    addProduct: "Add a product…",
    otherProduct: "Other (specify)",
    productName: "Product name",
    add: "Add",
    remove: "Remove",
    certs: "Certifications held",
    photos: "Photos / documents (optional)",
    photosHint: "Product photos, technical sheets, certifications",
    submit: "Send my application",
    requiredContact: "Please enter your company, contact person, email and country.",
    requiredCategory: "Please select at least one category.",
    requiredProduct: "Please enter at least one product you offer.",
    received: "Application received",
    receivedText: "Thank you for your application. Every file is carefully reviewed: our team will contact you within 10 business days for the next steps · discussions, product evaluation, audit.",
  },
  rdv: {
    screen: "Book a call with our expert",
    title: "Talk with Oumou Soumano",
    subtitle: "Supply chain & sourcing expert · Africa · Europe",
    duration: "Call duration",
    motif: "Purpose of the call",
    motifPlaceholder: "Select a purpose",
    pickDay: "Choose a day",
    slots: (day) => `Time slots · ${day}`,
    loadingSlots: "Loading availability…",
    noSlot: "No slot available on this day · please choose another day.",
    timezone: (tz) => `Detected time zone: ${tz}`,
    yourDetails: "Your details",
    name: "Name",
    company: "Company",
    companyPlaceholder: "Your company",
    email: "Email",
    emailPlaceholder: "you@company.com",
    confirming: "Confirming…",
    confirm: (day, slot) => `Confirm · ${day} at ${slot}`,
    slotTaken: "This slot has just been booked · please choose another one.",
    confirmed: "Appointment confirmed",
    confirmedText: (day, slot, dur) =>
      `Your call on ${day} at ${slot} (${dur} min) is confirmed. You will receive the video call link by email, along with options to cancel or reschedule.`,
  },
  product: {
    catalogue: "Catalogue",
    screen: "Product sheet",
    loading: "Loading…",
    notFound: "Product not found.",
    notFoundText: "This product is not in our catalogue · we can source it for you.",
    sourcing: "Custom sourcing",
    verified: "Verified",
    priceOnQuote: "Price on quotation",
    origin: "Origin",
    verifiedSupplier: "Verified supplier",
    packaging: "Packaging",
    moq: "Minimum order quantity (MOQ)",
    added: "Added",
    addToRequest: "+ Add to my request",
    requestQuote: "Request a quotation",
    protected: "Verified supplier · identity protected. No direct contact: Funti handles your quotation from start to finish.",
    description: "Description",
    benefits: "Benefits",
    others: "Other products",
    downloadAll: "Download the full catalogue",
    view: "View product",
  },
};

export const FORMS: Record<Lang, typeof fr> = { fr, en };
export const useFormsText = () => FORMS[useLang()];

// ─── Listes fixes : libellés anglais (la valeur envoyée reste la valeur française) ──

const OPTION_EN: Record<string, string> = {
  // Domaines d'activité
  "Agroalimentaire": "Food industry",
  "Distribution / Grossiste": "Retail / Wholesale",
  "Cosmétique": "Cosmetics",
  "Restauration / CHR": "Food service / HoReCa",
  "Industrie": "Industry",
  "Autre": "Other",
  "Autre / à définir": "Other / to be defined",
  // Délais
  "Dès que possible": "As soon as possible",
  "Sous 2 semaines": "Within 2 weeks",
  "Sous 1 mois": "Within 1 month",
  "1 à 3 mois": "1 to 3 months",
  "Flexible": "Flexible",
  // Conditionnements
  "Palettes": "Pallets",
  "Sacs": "Bags",
  "Cartons": "Cartons",
  "Vrac": "Bulk",
  // Livraison / prévisions
  "Afrique": "Africa",
  "Europe": "Europe",
  "par mois": "per month",
  "par an": "per year",
  // Rendez-vous
  "Projet d'importation": "Import project",
  "Recherche de fournisseurs": "Finding suppliers",
  "Logistique, formalités, certifications": "Logistics, formalities, certifications",
  // Catégories
  "Matières premières": "Raw materials",
  "Épicerie": "Grocery",
  "Épices": "Spices",
  "Boissons": "Beverages",
  "Fruits & légumes": "Fruits & vegetables",
  "Superaliments": "Superfoods",
  // Certifications
  "Bio UE": "EU Organic",
  "Bio": "Organic",
  "Casher": "Kosher",
  "Aucune": "None",
  // Incoterm « à conseiller »
  "À conseiller": "Advise me",
  // Espace fournisseur : statuts de stock, délais produit, emballages
  "En stock": "In stock",
  "Sur commande": "Made to order",
  "Rupture": "Out of stock",
  "Sous 1 semaine": "Within 1 week",
  "1 à 2 semaines": "1 to 2 weeks",
  "2 à 3 semaines": "2 to 3 weeks",
  "3 à 4 semaines": "3 to 4 weeks",
  "1 à 2 mois": "1 to 2 months",
  "Selon la récolte": "Depending on harvest",
  "À confirmer": "To be confirmed",
  "Autre (préciser)": "Other (specify)",
  "Sac": "Bag",
  "Carton": "Carton",
  "Bidon": "Jerrycan",
  "Seau": "Bucket",
  "Palette": "Pallet",
  "Conteneur 20'": "20' container",
  "Conteneur 40'": "40' container",
  "sacs": "bags",
  "cartons": "cartons",
  "bidons": "jerrycans",
  "seaux": "buckets",
  "palettes": "pallets",
  "conteneurs 20'": "20' containers",
  "conteneurs 40'": "40' containers",
};

// Pays absents (ou libellés autrement) dans Intl.DisplayNames.
const COUNTRY_EN_EXTRA: Record<string, string> = {
  "Birmanie (Myanmar)": "Myanmar (Burma)",
  "Congo": "Congo",
  "Congo (RDC)": "Congo (DRC)",
  "Kirghizistan": "Kyrgyzstan",
  "Palestine": "Palestine",
  "République tchèque": "Czech Republic",
  "Vatican": "Vatican City",
};

const normalizeName = (s: string) =>
  s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z]/g, "");

// Correspondance nom de pays français → anglais, construite une fois via le navigateur.
let countryEn: Map<string, string> | null = null;
function countryMap(): Map<string, string> {
  if (countryEn) return countryEn;
  countryEn = new Map();
  try {
    const fr = new Intl.DisplayNames(["fr"], { type: "region" });
    const en = new Intl.DisplayNames(["en"], { type: "region" });
    for (let a = 65; a < 91; a++) {
      for (let b = 65; b < 91; b++) {
        const code = String.fromCharCode(a, b);
        let name: string | undefined;
        try { name = fr.of(code); } catch { continue; }
        if (name && name !== code) countryEn.set(normalizeName(name), en.of(code) ?? name);
      }
    }
  } catch { /* navigateur sans Intl.DisplayNames : noms laissés en français */ }
  return countryEn;
}

/** Libellé anglais d'une valeur française (liste fixe ou pays) ; inchangé si inconnu. */
export function optionLabelEn(value: string): string {
  return OPTION_EN[value] ?? COUNTRY_EN_EXTRA[value] ?? countryMap().get(normalizeName(value)) ?? value;
}

/** Traduit l'affichage d'une valeur de liste selon la langue courante. */
export function useOptionLabel(): (value: string) => string {
  const lang = useLang();
  return useCallback((value: string) => (lang === "en" ? optionLabelEn(value) : value), [lang]);
}

// ─── Aide incoterms ──────────────────────────────────────────────────────────

export const INCOTERM_INFO_EN: Record<string, string> = {
  "EXW": "Ex Works · You handle everything: pickup at the factory, export customs, main transport and import customs. Maximum risk.",
  "FCA": "Free Carrier · The seller clears export customs and hands the goods to the carrier at origin; you handle the main transport.",
  "FAS": "Free Alongside Ship · The seller delivers alongside the ship at the port of departure; you take over from there.",
  "FOB": "Free On Board · The seller loads the goods on board at the port of departure; you handle freight and arrival. A good compromise.",
  "CFR": "Cost & Freight · The seller pays freight to the port of arrival; the risk passes to you once loaded.",
  "CIF": "Cost, Insurance & Freight · Like CFR, with insurance paid by the seller up to the port of arrival.",
  "CPT": "Carriage Paid To · The seller pays transport to the agreed place; risk passes at the first carrier.",
  "CIP": "Carriage & Insurance Paid To · Like CPT, with insurance up to the agreed place.",
  "DPU": "Delivered at Place Unloaded · The seller delivers and unloads the goods at the agreed place.",
  "DAP": "Delivered at Place · The seller delivers to you; you only pay import duties on arrival.",
  "DDP": "Delivered Duty Paid · Turnkey delivery: the seller pays everything, including your local taxes.",
  "À conseiller": "Not sure which one to choose? Tell us: we will recommend the Incoterm best suited to your project.",
};

export const INCOTERM_STRATEGIES_EN = [
  { emoji: "🚨", title: "Maximum risk · EXW", text: "You handle everything: carrier at the factory, customs, transport. A customs hold-up or damage is at your expense. Best avoided if you are new to importing." },
  { emoji: "🤝", title: "Balance & control · FCA / FOB", text: "The seller clears export customs and delivers to the port or airport of departure; you take over. The best compromise: you control international transport without handling the seller's country formalities." },
  { emoji: "🛋️", title: "Total comfort · DAP / DDP", text: "The seller ships all the way to your premises. With DAP you pay duties on arrival; with DDP everything is included (turnkey). Watch out: transport is re-invoiced, often with a margin." },
];
