/** Textes bilingues (FR/EN) de la page de connexion et de l'espace fournisseur.
 *  `useSupplierText()` renvoie le dictionnaire de la langue courante (lib/i18n).
 *  Les dictionnaires `fr` et `en` DOIVENT avoir exactement la même forme.
 */

import { useLang, type Lang } from "@/lib/i18n";

const plural = (n: number, one: string, many: string) => (n > 1 ? many : one);

const fr = {
  login: {
    screen: "Connexion",
    title: "Connexion",
    subtitle: "Espace fournisseurs et administration.",
    email: "Adresse e-mail",
    emailPlaceholder: "vous@entreprise.com",
    password: "Mot de passe",
    submit: "Se connecter",
    submitting: "Connexion…",
    invalid: "Identifiants invalides. Vérifiez votre e-mail et votre mot de passe.",
    forgot: "Mot de passe oublié ? Contactez l'équipe Funti pour le réinitialiser.",
    notListed: "Pas encore référencé ?",
    apply: "Candidatez ici",
  },
  shell: {
    nav: {
      dashboard: "Tableau de bord",
      products: "Produits & stocks",
      propose: "Proposer un produit",
      dossier: "Mon dossier",
      settings: "Paramètres",
    },
    role: "Fournisseur",
    fallbackName: "Fournisseur",
    close: "Fermer",
    menu: "Menu",
    logout: "Se déconnecter",
    backToSite: "Retour au site",
    site: "Site",
  },
  common: {
    loading: "Chargement…",
    back: "Retour",
    cancel: "Annuler",
    save: "Enregistrer",
    saving: "Enregistrement…",
    genericError: "Une erreur est survenue. Réessayez.",
    saveError: "Échec de l'enregistrement. Réessayez.",
    uploadError: "Téléversement impossible.",
    uploading: "Envoi…",
    photoFormats: "JPG, PNG ou WebP · 5 Mo maximum.",
    removePhoto: "Retirer la photo",
    notProvided: "Non renseigné",
    notSpecified: "Non précisé",
    select: "Sélectionner…",
    reset: "Réinitialiser",
    internalOnly: "Visibles uniquement par vous et l'équipe Funti · jamais affichées publiquement.",
    nameRequired: "Le nom du produit est requis.",
    descriptionRequired: "Une description est requise.",
  },
  fields: {
    photo: "Photo du produit",
    productName: "Nom du produit",
    productNamePlaceholder: "Beurre de karité brut",
    category: "Catégorie",
    origin: "Origine",
    availableUntil: "Disponible jusqu'au (facultatif)",
    removeLimit: "Retirer la limite",
    availableUntilHint: "À cette date, le produit se retire automatiquement du site. Vous et l'équipe Funti êtes alertés 3 jours avant. Laissez vide s'il est disponible en continu.",
    description: "Description",
    descriptionPlaceholder: "Caractéristiques, usage, origine exacte…",
    benefits: "Bienfaits",
    benefitsPlaceholder: "Apports nutritionnels, atouts pour l'acheteur…",
    commercialInternal: "Informations commerciales · internes",
    pricePerKg: "Prix au kilo",
    pricePerKgPlaceholder: "Ex : 1 200 FCFA/kg",
    bulkPrice: "Prix en vrac",
    bulkPricePlaceholder: "Ex : 950 FCFA/kg dès 1 t",
    harvest: "Période de récolte",
    harvestPlaceholder: "Ex : novembre à février",
    packaging: "Conditionnement",
    moq: "Quantité minimum (MOQ)",
    availableUntilShort: "Disponible jusqu'au",
    expired: "(expiré)",
  },
  dashboard: {
    hello: (name: string) => `Bonjour${name ? ` ${name}` : ""}`,
    intro: "Voici l'état de votre espace fournisseur.",
    nextAction: "Prochaine action",
    firstProductTitle: "Référencez votre premier produit",
    firstProductBody: "Proposez une première fiche · notre équipe la validera avant publication.",
    firstProductCta: "Proposer un produit",
    staleTitle: (n: number) => `Actualisez ${n} référence${plural(n, "", "s")}`,
    staleBody: (n: number, days: number) =>
      `${plural(n, "Elle n'a", "Elles n'ont")} pas été mise${plural(n, "", "s")} à jour depuis plus de ${days} jours. Confirmez le stock pour rester visible auprès des acheteurs.`,
    staleCta: "Mettre à jour mes stocks",
    ruptureTitle: (n: number) => `${n} référence${plural(n, "", "s")} en rupture`,
    ruptureBody: "Réapprovisionnez au plus vite, puis mettez à jour la disponibilité dès que le produit est de nouveau en stock.",
    seeProducts: "Voir mes produits",
    dossierTitle: (pct: number) => `Complétez votre dossier (${pct} %)`,
    dossierBody: "Un dossier complet inspire confiance et accélère la mise en relation.",
    dossierCta: "Compléter mon dossier",
    allGoodTitle: "Tout est à jour",
    allGoodBody: "Vos stocks sont actualisés et votre dossier est complet. Merci !",
    kpiActive: "Références actives",
    kpiDetention: "Taux de détention",
    kpiInStock: (inStock: number, total: number) => `${inStock}/${total} en stock`,
    kpiStale: (days: number) => `À actualiser (+${days} j)`,
    kpiStockUpToDate: "Stocks à jour",
    kpiRupture: "En rupture",
    kpiDossier: "Complétude du dossier",
    staleCard: "Stocks non actualisés",
    noStale: (days: number) => `Aucune référence à actualiser · tous vos stocks datent de moins de ${days} jours.`,
    updatedOn: (date: string, days: number) => `Actualisé le ${date} · il y a ${days} j`,
    seeAllStale: (n: number) => `Voir les ${n} références →`,
    dossierCard: "Complétude du dossier",
  },
  dossier: {
    name: "Nom de la société",
    contact: "Nom du contact",
    phone: "Téléphone",
    country: "Pays",
    city: "Ville",
    products: "Au moins un produit référencé",
  },
  coordonnees: {
    title: "Mon dossier",
    intro: "Tenez à jour les informations de votre société. Votre e-mail de connexion et vos catégories sont gérés par l'équipe Funti.",
    loading: "Chargement de votre profil…",
    loginEmail: "E-mail de connexion",
    changeEmail: "Pour changer d'e-mail, contactez l'équipe Funti.",
    company: "Nom de la société",
    contact: "Nom du contact",
    phone: "Téléphone",
    country: "Pays",
    city: "Ville",
    saved: "Coordonnées enregistrées.",
    submit: "Enregistrer mon dossier",
  },
  password: {
    title: "Paramètres",
    intro: "Gérez la sécurité de votre compte. Si vous vous êtes connecté avec un mot de passe temporaire, remplacez-le par un mot de passe personnel (8 caractères minimum).",
    card: "Mot de passe",
    current: "Mot de passe actuel",
    next: "Nouveau mot de passe",
    nextPlaceholder: "8 caractères min.",
    confirm: "Confirmation",
    confirmPlaceholder: "Répétez-le",
    show: "Afficher les mots de passe",
    tooShort: "Le nouveau mot de passe doit contenir au moins 8 caractères.",
    mismatch: "La confirmation ne correspond pas au nouveau mot de passe.",
    wrongCurrent: "Mot de passe actuel incorrect.",
    saved: "Mot de passe mis à jour.",
    submit: "Changer mon mot de passe",
  },
  products: {
    title: "Produits & stocks",
    activeCount: (n: number) => `${n} référence${plural(n, "", "s")} active${plural(n, "", "s")}`,
    toRefresh: (n: number) => `${n} à actualiser`,
    propose: "Proposer un produit",
    searchPlaceholder: "Rechercher un produit · nom, référence, origine, catégorie…",
    clear: "Effacer",
    all: "Tous",
    stale: "À actualiser",
    allCategories: "Toutes catégories",
    staleWarning: (n: number, days: number) =>
      `${n > 1 ? `${n} références ne sont` : "1 référence n'est"} pas actualisée${plural(n, "", "s")} depuis plus de ${days} jours. Confirmez le stock pour rester visible auprès des acheteurs.`,
    loading: "Chargement de vos produits…",
    none: "Aucun produit rattaché à votre compte pour le moment.",
    noMatch: (query: string) => `Aucun produit ne correspond ${query ? `à « ${query} »` : "à ces filtres"}.`,
    results: (n: number, total: number) => `${n} résultat${plural(n, "", "s")} sur ${total}`,
    stock: "Stock",
    delay: "Délai",
    updatedOn: (date: string) => `Màj le ${date}`,
    ruptureNotice: "En rupture · réapprovisionnez au plus vite. Mettez à jour le stock dès que le produit est de nouveau disponible pour rester visible auprès des acheteurs.",
    details: "Détails",
    editSheet: "Modifier la fiche",
    updateStock: "Mettre à jour le stock",
    remove: "Retirer",
    removeTitle: "Retirer de la vente (récupérable)",
    availability: "Disponibilité",
    stockUnit: (unit: string) => `Stock (${unit})`,
    equivalent: (text: string) => `Soit ${text}.`,
    delayIndicative: "Délai indicatif",
    delayOther: "Autre (préciser)",
    delayOtherPlaceholder: "Ex : sous 10 jours, selon récolte…",
    hintRupture: "Rupture : le stock est mis à 0. Repassez en « En stock » dès que le produit est de nouveau disponible.",
    hintOnOrder: "Sur commande : produit fabriqué ou livré à la demande · le stock peut rester à 0.",
    hintInStock: (unit: string) => `En stock : indiquez la quantité réellement disponible (en ${unit}), supérieure à 0.`,
    inStockNeedsQty: "Un produit « En stock » doit avoir une quantité supérieure à 0 · choisissez « Sur commande » ou « Rupture ».",
    ruptureSaved: "Rupture enregistrée · pensez à réapprovisionner au plus vite.",
    updateSaved: (date: string) => `Mise à jour enregistrée le ${date}`,
    saveFailed: "Échec de l'enregistrement · réessayez.",
    confirmRemoveTitle: (name: string) => `Retirer « ${name} » de la vente ?`,
    confirmRemoveMessage: "Il quittera le catalogue mais restera récupérable dans « Produits retirés ».",
    removed: "Produit retiré · l'équipe Funti a été prévenue.",
    removeFailed: "Échec du retrait · réessayez.",
    restored: "Produit restauré.",
    restoreFailed: "Échec de la restauration · réessayez.",
    showArchived: "Voir les produits retirés",
    hideArchived: "Masquer les produits retirés",
    noArchived: "Aucun produit retiré.",
    restore: "Restaurer",
    sheetUpdated: "Fiche produit mise à jour.",
  },
  edit: {
    title: "Modifier la fiche produit",
    changePhoto: "Changer la photo",
    submit: "Enregistrer les modifications",
  },
  propose: {
    title: "Proposer un produit",
    intro: "Soumettez une fiche complète. Aucun produit n'est publié automatiquement : l'équipe Funti examine chaque proposition.",
    submit: "Soumettre à validation",
    footNote: "Aucune publication automatique · validation par l'équipe Funti.",
    stepProduct: "Le produit",
    stepProductHint: "Identité",
    pickProduct: "Sélectionnez ou saisissez le produit.",
    choosePhoto: "Choisir une photo",
    product: "Produit",
    selectProduct: "Sélectionner un produit…",
    other: "Autre (préciser)",
    stepPackaging: "Conditionnement & quantités",
    stepPackagingHint: "Format, MOQ, volume",
    volume: "Volume disponible (capacité de production)",
    volumePlaceholder: "Ex : 2 000 kg / mois",
    availableUntilHint: "Si votre produit n'est disponible qu'un temps limité, indiquez la date de fin. Il se retirera automatiquement du site à cette date. Vous et l'équipe Funti serez alertés 3 jours avant. Laissez vide s'il est disponible en continu.",
    stepPrice: "Prix & récolte",
    stepPriceHint: "Confidentiel",
    commercialConfidential: "Informations commerciales · confidentielles",
    confidentialNote: "Ces informations restent internes à Funti et ne sont jamais affichées publiquement.",
    stepPresentation: "Présentation",
    stepPresentationHint: "Description & certifications",
    certs: "Certifications détenues pour ce produit",
    sentScreen: "Proposition envoyée",
    sentTitle: "Proposition transmise",
    sentText: "Votre proposition a été transmise à l'équipe Funti pour validation. Vous serez informé par e-mail de la décision. Aucune publication automatique.",
    backToProducts: "Retour à mes produits",
  },
  packaging: {
    label: "Conditionnement (format de vente)",
    moq: "MOQ · quantité minimum de commande",
    moqPreview: (text: string) => `→ MOQ : ${text}`,
    moqHint: (plural: string, unit: string) =>
      `Choisissez « ${plural} » pour saisir la MOQ en nombre de colis · l'équivalent en ${unit} est calculé.`,
  },
  availability: {
    expired: "Disponibilité expirée",
    today: "Se retire aujourd'hui",
    inDays: (days: number) => `Se retire dans ${days} j`,
    until: (date: string) => `Dispo jusqu'au ${date}`,
  },
};

const en: typeof fr = {
  login: {
    screen: "Sign in",
    title: "Sign in",
    subtitle: "Supplier and administration area.",
    email: "Email address",
    emailPlaceholder: "you@company.com",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    invalid: "Invalid credentials. Please check your email and password.",
    forgot: "Forgot your password? Contact the Funti team to reset it.",
    notListed: "Not listed yet?",
    apply: "Apply here",
  },
  shell: {
    nav: {
      dashboard: "Dashboard",
      products: "Products & stock",
      propose: "Propose a product",
      dossier: "My profile",
      settings: "Settings",
    },
    role: "Supplier",
    fallbackName: "Supplier",
    close: "Close",
    menu: "Menu",
    logout: "Sign out",
    backToSite: "Back to website",
    site: "Site",
  },
  common: {
    loading: "Loading…",
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    genericError: "Something went wrong. Please try again.",
    saveError: "Could not save. Please try again.",
    uploadError: "Upload failed.",
    uploading: "Uploading…",
    photoFormats: "JPG, PNG or WebP · 5 MB maximum.",
    removePhoto: "Remove photo",
    notProvided: "Not provided",
    notSpecified: "Not specified",
    select: "Select…",
    reset: "Reset",
    internalOnly: "Visible only to you and the Funti team · never shown publicly.",
    nameRequired: "The product name is required.",
    descriptionRequired: "A description is required.",
  },
  fields: {
    photo: "Product photo",
    productName: "Product name",
    productNamePlaceholder: "Raw shea butter",
    category: "Category",
    origin: "Origin",
    availableUntil: "Available until (optional)",
    removeLimit: "Remove the limit",
    availableUntilHint: "On this date, the product is automatically removed from the site. You and the Funti team are notified 3 days before. Leave empty if it is always available.",
    description: "Description",
    descriptionPlaceholder: "Characteristics, use, exact origin…",
    benefits: "Benefits",
    benefitsPlaceholder: "Nutritional value, advantages for the buyer…",
    commercialInternal: "Commercial information · internal",
    pricePerKg: "Price per kg",
    pricePerKgPlaceholder: "e.g. 1,200 FCFA/kg",
    bulkPrice: "Bulk price",
    bulkPricePlaceholder: "e.g. 950 FCFA/kg from 1 t",
    harvest: "Harvest period",
    harvestPlaceholder: "e.g. November to February",
    packaging: "Packaging",
    moq: "Minimum order quantity (MOQ)",
    availableUntilShort: "Available until",
    expired: "(expired)",
  },
  dashboard: {
    hello: (name) => `Hello${name ? ` ${name}` : ""}`,
    intro: "Here is the status of your supplier area.",
    nextAction: "Next action",
    firstProductTitle: "List your first product",
    firstProductBody: "Propose a first product sheet · our team will validate it before publication.",
    firstProductCta: "Propose a product",
    staleTitle: (n) => `Update ${n} product${plural(n, "", "s")}`,
    staleBody: (n, days) =>
      `${plural(n, "It has", "They have")} not been updated for more than ${days} days. Confirm your stock to stay visible to buyers.`,
    staleCta: "Update my stock",
    ruptureTitle: (n) => `${n} product${plural(n, "", "s")} out of stock`,
    ruptureBody: "Restock as soon as possible, then update availability as soon as the product is back in stock.",
    seeProducts: "See my products",
    dossierTitle: (pct) => `Complete your profile (${pct}%)`,
    dossierBody: "A complete profile builds trust and speeds up matching with buyers.",
    dossierCta: "Complete my profile",
    allGoodTitle: "Everything is up to date",
    allGoodBody: "Your stock is up to date and your profile is complete. Thank you!",
    kpiActive: "Active products",
    kpiDetention: "In-stock rate",
    kpiInStock: (inStock, total) => `${inStock}/${total} in stock`,
    kpiStale: (days) => `To update (+${days} d)`,
    kpiStockUpToDate: "Stock up to date",
    kpiRupture: "Out of stock",
    kpiDossier: "Profile completeness",
    staleCard: "Stock not updated",
    noStale: (days) => `Nothing to update · all your stock was updated less than ${days} days ago.`,
    updatedOn: (date, days) => `Updated on ${date} · ${days} d ago`,
    seeAllStale: (n) => `See all ${n} products →`,
    dossierCard: "Profile completeness",
  },
  dossier: {
    name: "Company name",
    contact: "Contact name",
    phone: "Phone",
    country: "Country",
    city: "City",
    products: "At least one listed product",
  },
  coordonnees: {
    title: "My profile",
    intro: "Keep your company information up to date. Your login email and categories are managed by the Funti team.",
    loading: "Loading your profile…",
    loginEmail: "Login email",
    changeEmail: "To change your email, contact the Funti team.",
    company: "Company name",
    contact: "Contact name",
    phone: "Phone",
    country: "Country",
    city: "City",
    saved: "Details saved.",
    submit: "Save my profile",
  },
  password: {
    title: "Settings",
    intro: "Manage your account security. If you signed in with a temporary password, replace it with a personal one (at least 8 characters).",
    card: "Password",
    current: "Current password",
    next: "New password",
    nextPlaceholder: "8 characters min.",
    confirm: "Confirmation",
    confirmPlaceholder: "Repeat it",
    show: "Show passwords",
    tooShort: "The new password must be at least 8 characters long.",
    mismatch: "The confirmation does not match the new password.",
    wrongCurrent: "Incorrect current password.",
    saved: "Password updated.",
    submit: "Change my password",
  },
  products: {
    title: "Products & stock",
    activeCount: (n) => `${n} active product${plural(n, "", "s")}`,
    toRefresh: (n) => `${n} to update`,
    propose: "Propose a product",
    searchPlaceholder: "Search a product · name, reference, origin, category…",
    clear: "Clear",
    all: "All",
    stale: "To update",
    allCategories: "All categories",
    staleWarning: (n, days) =>
      `${n > 1 ? `${n} products have` : "1 product has"} not been updated for more than ${days} days. Confirm your stock to stay visible to buyers.`,
    loading: "Loading your products…",
    none: "No product linked to your account yet.",
    noMatch: (query) => `No product matches ${query ? `"${query}"` : "these filters"}.`,
    results: (n, total) => `${n} result${plural(n, "", "s")} out of ${total}`,
    stock: "Stock",
    delay: "Lead time",
    updatedOn: (date) => `Updated ${date}`,
    ruptureNotice: "Out of stock · restock as soon as possible. Update the stock as soon as the product is available again to stay visible to buyers.",
    details: "Details",
    editSheet: "Edit product sheet",
    updateStock: "Update stock",
    remove: "Remove",
    removeTitle: "Remove from sale (recoverable)",
    availability: "Availability",
    stockUnit: (unit) => `Stock (${unit})`,
    equivalent: (text) => `That is ${text}.`,
    delayIndicative: "Indicative lead time",
    delayOther: "Other (specify)",
    delayOtherPlaceholder: "e.g. within 10 days, depending on harvest…",
    hintRupture: "Out of stock: stock is set to 0. Switch back to \"In stock\" as soon as the product is available again.",
    hintOnOrder: "Made to order: produced or delivered on demand · stock can stay at 0.",
    hintInStock: (unit) => `In stock: enter the quantity actually available (in ${unit}), greater than 0.`,
    inStockNeedsQty: "An \"In stock\" product must have a quantity greater than 0 · choose \"Made to order\" or \"Out of stock\".",
    ruptureSaved: "Out of stock saved · remember to restock as soon as possible.",
    updateSaved: (date) => `Update saved on ${date}`,
    saveFailed: "Could not save · please try again.",
    confirmRemoveTitle: (name) => `Remove "${name}" from sale?`,
    confirmRemoveMessage: "It will leave the catalogue but can be recovered from \"Removed products\".",
    removed: "Product removed · the Funti team has been notified.",
    removeFailed: "Could not remove · please try again.",
    restored: "Product restored.",
    restoreFailed: "Could not restore · please try again.",
    showArchived: "Show removed products",
    hideArchived: "Hide removed products",
    noArchived: "No removed product.",
    restore: "Restore",
    sheetUpdated: "Product sheet updated.",
  },
  edit: {
    title: "Edit product sheet",
    changePhoto: "Change photo",
    submit: "Save changes",
  },
  propose: {
    title: "Propose a product",
    intro: "Submit a complete product sheet. Nothing is published automatically: the Funti team reviews every proposal.",
    submit: "Submit for review",
    footNote: "No automatic publication · reviewed by the Funti team.",
    stepProduct: "The product",
    stepProductHint: "Identity",
    pickProduct: "Select or enter the product.",
    choosePhoto: "Choose a photo",
    product: "Product",
    selectProduct: "Select a product…",
    other: "Other (specify)",
    stepPackaging: "Packaging & quantities",
    stepPackagingHint: "Format, MOQ, volume",
    volume: "Available volume (production capacity)",
    volumePlaceholder: "e.g. 2,000 kg / month",
    availableUntilHint: "If your product is only available for a limited time, enter the end date. It will be automatically removed from the site on that date. You and the Funti team will be notified 3 days before. Leave empty if it is always available.",
    stepPrice: "Price & harvest",
    stepPriceHint: "Confidential",
    commercialConfidential: "Commercial information · confidential",
    confidentialNote: "This information stays internal to Funti and is never shown publicly.",
    stepPresentation: "Presentation",
    stepPresentationHint: "Description & certifications",
    certs: "Certifications held for this product",
    sentScreen: "Proposal sent",
    sentTitle: "Proposal submitted",
    sentText: "Your proposal has been sent to the Funti team for review. You will be informed of the decision by email. Nothing is published automatically.",
    backToProducts: "Back to my products",
  },
  packaging: {
    label: "Packaging (sales format)",
    moq: "MOQ · minimum order quantity",
    moqPreview: (text) => `→ MOQ: ${text}`,
    moqHint: (plural, unit) =>
      `Choose "${plural}" to enter the MOQ as a number of packages · the equivalent in ${unit} is calculated.`,
  },
  availability: {
    expired: "Availability expired",
    today: "Removed today",
    inDays: (days) => `Removed in ${days} d`,
    until: (date) => `Available until ${date}`,
  },
};

export const SUPPLIER_TEXT: Record<Lang, typeof fr> = { fr, en };
export const useSupplierText = () => SUPPLIER_TEXT[useLang()];
